POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName": "Antonio",
    "lastName": "Foti",
    "email": "antonioafoti",
    "favoriteColor": "red",
    "birthday": "2023-03-03"
}
